---
- name: 
  hosts: all
  vars:
    ansible_sudo_pass: "{{ linux.oper_password }}"
    ansible_user: "{{ linux.oper_user }}"
  become: yes
  roles:
    - raspbian_prep
    - wireless
    - tunnel
    - ccb_backup
    - bells
