---
- name: Reset any crud around aptitude locks
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/var/lib/apt/lists/lock"
    - "/var/cache/apt/archives/lock"

- name: Install required OS packages
  apt: name={{ item }} state=latest
  with_items:
  - python-pip
  - git
  - ntp
  - zip
  - aptitude

- name: Update apt cache and upgrade all existing modules
  apt:
    upgrade: yes

- name: Set the correct timezone
  file:
    src: "/usr/share/zoneinfo/{{ ntp_timezone }}"
    dest: /etc/localtime
    state: link
    force: yes

- name: Ensure NTP is running and enabled at system start.
  service:
    name: ntp
    state: started
    enabled: yes
  when: ntp_enabled

- name: Ensure NTP is stopped and disabled at system start.
  service:
    name: ntp
    state: stopped
    enabled: no
  when: not ntp_enabled

- name: Ensure pip is installed and up-to-date
  pip: name={{ item }} state=latest
  with_items:
  - pip
