---
- name: Reset any crud around aptitude locks
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/var/lib/apt/lists/lock"
    - "/var/cache/apt/archives/lock"

- name: Install required OS packages
  apt: name={{ item }} state=latest
  with_items:
  - python3-pip
  - git
  - ntp
  - zip
  - aptitude
  - acl

- name: Update apt cache and upgrade all existing modules
  apt:
    upgrade: yes

- name: Set up cron to automatically run updates and upgrades going forward
  cron:
    name: "Run apt updates and upgrades every Wed 4am"
    user: "root"
    minute: "0"
    hour: "4"
    weekday: "3"
    job: "/usr/bin/apt update && /usr/bin/apt upgrade -y"

- name: Set up cron to sync real-time clock
  cron:
    name: "Resync hardware clock daily 6am"
    user: "root"
    minute: "0"
    hour: "6"
    job: "/sbin/hwclock --systohc"

- name: Set the correct timezone
  file:
    src: "/usr/share/zoneinfo/{{ ntp_timezone }}"
    dest: /etc/localtime
    state: link
    force: yes

- name: Ensure NTP is running and enabled at system start.
  service:
    name: ntp
    state: started
    enabled: yes
  when: ntp_enabled

- name: Ensure NTP is stopped and disabled at system start.
  service:
    name: ntp
    state: stopped
    enabled: no
  when: not ntp_enabled

- name: Ensure pip is installed and up-to-date
  pip: name={{ item }} state=latest
  with_items:
  - pip
